# Generated by Django 5.2.15 on 2026-06-20 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number_of_rows', models.IntegerField(help_text='Number of rows in the hall, e.g. 10')),
                ('seats_per_row', models.IntegerField(help_text='Number of seats per row, e.g. 12')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='theaters.theaterhall')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(help_text='e.g. A, B, C', max_length=5)),
                ('seat_number', models.IntegerField(help_text='e.g. 1, 2, 3')),
                ('seat_identifier', models.CharField(help_text='e.g. A1, A2', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theaters.theaterhall')),
            ],
            options={
                'unique_together': {('hall', 'seat_identifier')},
            },
        ),
    ]
