# Generated by Django 5.2.15 on 2026-06-20 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cast', models.TextField(help_text='Comma-separated cast members')),
                ('director', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('reviews', models.TextField(blank=True, help_text='Mock user reviews or reviews summary', null=True)),
                ('trailer_image', models.CharField(help_text='URL of the trailer thumbnail image', max_length=500)),
                ('trailer_video_url', models.URLField(help_text='URL of the trailer video')),
                ('mpaa_rating', models.CharField(help_text='e.g. PG, PG-13, R', max_length=10)),
                ('status', models.CharField(choices=[('CURRENTLY_PLAYING', 'Currently Playing'), ('COMING_SOON', 'Coming Soon')], default='CURRENTLY_PLAYING', max_length=20)),
                ('release_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='movies.movie')),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
